version: "3.9"
services:
    web:
        build: .
        ports:
            - "5001:5000"
        restart: always
        depends_on: [db]
        volumes:
          - api-database:/var/www/asp.net
    db:
        image: mysql:8.0
        environment:
          MYSQL_ROOT_PASSWORD: 'please-set-a-password'
        ports:
          - '3307:3306'
        expose:
          - '3306'
        hostname: novaapi_mysql
        volumes:
          - mysql-database:/var/lib/mysql
volumes: 
  mysql-database:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/my/path/to/mysql'
      # device: 'data/mysql'
  api-database:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/my/path/to/api-data'
      # device: 'data/api-data'